### ISSUE TITLE
Will it support A3 flight controller?

### ISSUE THREAD

**Issue by SiuKeungm** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#3]

**Comment by USTfgaoaa** [comment]
@SiuKeungm 
The controller supports A3 perfectly. 
But the intermediate layer, djiros, may have some issues. It depends on the version of the onboard SDK (OSDK). As far as I know, OSDK version < 3.3 suits it. But for a new A3 with the latest firmware (it corresponds to OSDK 3.7 or 3.8), it may not work.

So, the conclusion is, the 'n3ctrl' is good, but the 'djiros' may not be good. But I believe it can be fixed by slightly modify some interface.

**Comment by ziv-lin** [comment]
Hey, you can type `git checkout 3.3` to fix the compile errors. 
Shown as following~
![dji_ros](https://user-images.githubusercontent.com/9316645/60728942-23f82b00-9f74-11e9-9fa9-b51bf0ac1722.png)

**Comment by SiuKeungm** [comment]
@USTfgaoaa @ziv-lin Thanks for your reply. I will try it!
