### ISSUE TITLE
Is it possible to make the sdf_map moving with the robot?

### ISSUE THREAD

**Issue by ChengeYang** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#7]
Hi,

Thanks for the help last time! I've got another problem regarding sdf_map.

I'm trying to fly the drone in a large environment. It requires the map_size to be really big and takes too much memory. So I'm thinking to make the occupancy_buffer moving with the robot instead of being static (fram_id =  "map"). In this way, the map size can be significantly reduced.

Currently if I make the frame_id to be the robot frame, the map can move with the robot but the generated pointcloud is not transformed correctly.

Do you have any idea how I can do it?
Thanks.

**Comment by USTfgaoaa** [comment]
@ChengeYang 

Your problem is just about whether to keep or forget the historical map of what the drone explored. If you don't want to keep a large global map data buffer, just maintain a smaller buffer along with the drone's movements for local planning, you should keep fusing and cleaning the data on your local map and calculate the ESDF of this local map every tick you want to update it. You may take Ewok(https://github.com/VladyslavUsenko/ewok) as a reference.

The change of the frame_id has no effect but only affects the visualization in Rviz.

**Comment by ChengeYang** [comment]
I'll close this issue now. Thanks!
